// Generated by Neo

#ifndef _COMMONS_DROID_WRAPPER_H_
#define _COMMONS_DROID_WRAPPER_H_

#include <commons/defines.h>

#ifdef _ANDROID_PLATFORM_
#include <jni.h>

namespace commons {
extern JavaVM* g_vm;
JNIEnv* gen_attached_env(JavaVM* jvm, jint version, jboolean* need_detach);
}

#endif /* _ANDROID_PLATFORM_ */
#endif /* _UTILS_DROID_WRAPPER_H_ */
