#!/bin/bash

version='0.3.3a'
revision=`git rev-parse --short HEAD`
build_date=`date +"%Y-%m-%d"`

header='revision.h'

echo "// Generated by Neo" > ${header}
echo "" >> ${header}
echo "#define REVISION \"[${version}-${revision}-${build_date}]\"" >> ${header}

