// Generated by Neo

#include <commons/handler.h>

#include <commons/handler_body.h>

namespace commons {
Handler::Handler() { body_ = new HandlerBody(this); }
Handler::~Handler() { delete body_; }

bool Handler::send(int what, int arg1, int arg2, void* obj) {
    return body_->send(what, arg1, arg2, obj);
}
} /* namespace: commons */
