// Generated by Neo

#ifndef _COMMONS_MESSAGE_H_
#define _COMMONS_MESSAGE_H_

#include <commons/defines.h>

namespace commons {
class Message {
   public:
    Message(int what, int arg1, int arg2, void* obj, int offset = 0) {
        what_ = what;
        arg1_ = arg1;
        arg2_ = arg2;
        obj_ = obj;
        offset_ = offset;
    }
    virtual ~Message() {}

    inline int what() const { return what_; }
    inline int arg1() const { return arg1_; }
    inline int arg2() const { return arg2_; }
    inline void* obj() { return obj_; }

    inline int offset() const { return offset_; }

   private:
    int what_;
    int arg1_;
    int arg2_;
    void* obj_;

    int offset_;

    ONLY_CUSTOM_CONSTRUCTION(Message);
};
} /* namespace: commons */

#endif /* _COMMONS_MESSAGE_H_ */
